name: Build All Submodules

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build All Modules
        run: ./gradlew assembleRelease || ./gradlew build

      - name: Upload Zip Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Pixelify-Modules
          path: |
            **/build/outputs/**/*.zip
            **/build/zip/*.zip
            **/out/*.zip
